[project]
name = "youtubetomp3-telegrambot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.19.0",
    "requests>=2.32.3",
    "yt-dlp>=2025.3.31",
]
